function presentationPlotDist_s1c()
    frames = [2 4 10 35 45];
    parms = make_parms( ...
        'frames', frames, ...
        'hist_bin', 0.04, ...
        'estimate_bin_sec', 1 ...
    );
    data = loadData('s1c',1);
    numActiveDist(data,parms);
    legend off;
    textPos = [ ...
        0.694, 0.077; ...
        0.042, 0.49; ...
        0.092, 0.141; ...
        0.527, 0.155; ...
        0.519, 0.266; ...
    ];
    for i=1:length(frames)
        dclr = (i-1)/(length(frames)-1);
        clr = [dclr 0 1-dclr];
        t = sprintf('Hour %d', frames(i));
        text(textPos(i,1), textPos(i,2), t, 'Color', clr, 'FontSize', 14, 'FontWeight', 'bold')
    end
end
